export default [
  {
    id: 1,
    name: "Helen Mitchell",
    email: "Lawson.Bergnaum74@gmail.com",
    phone: "595-935-1788 x617",
    avatar: "https://cdn.fakercloud.com/avatars/supjoey_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Fiat Fortwo",
        color: "plum",
        mileage: 91279,
        st: "Connecticut",
      },
      {
        id: 2,
        designation: "Ford Camry",
        color: "gold",
        mileage: 51662,
        st: "Kentucky",
      },
    ],
  },
  {
    id: 2,
    name: "Andres Ankunding II",
    email: "Ally.Osinski@hotmail.com",
    phone: "220.605.1359",
    avatar: "https://cdn.fakercloud.com/avatars/osmanince_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Audi Camry",
        color: "cyan",
        mileage: 80824,
        st: "Colorado",
      },
    ],
  },
  {
    id: 3,
    name: "Bridget Littel MD",
    email: "Keyon_Kulas@hotmail.com",
    phone: "743-543-0009 x425",
    avatar: "https://cdn.fakercloud.com/avatars/vivekprvr_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Smart Mustang",
        color: "blue",
        mileage: 48745,
        st: "Montana",
      },
      {
        id: 2,
        designation: "Bugatti Explorer",
        color: "pink",
        mileage: 74158,
        st: "Pennsylvania",
      },
    ],
  },
  {
    id: 4,
    name: "Bennie Nikolaus",
    email: "Cedrick.Crooks39@gmail.com",
    phone: "1-292-568-1766 x98333",
    avatar: "https://cdn.fakercloud.com/avatars/javorszky_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Smart CTS",
        color: "olive",
        mileage: 18347,
        st: "Texas",
      },
      {
        id: 2,
        designation: "Rolls Royce ATS",
        color: "purple",
        mileage: 89486,
        st: "North Carolina",
      },
      {
        id: 3,
        designation: "Chevrolet Model T",
        color: "blue",
        mileage: 80191,
        st: "New York",
      },
      {
        id: 4,
        designation: "Cadillac LeBaron",
        color: "turquoise",
        mileage: 26399,
        st: "Missouri",
      },
      {
        id: 5,
        designation: "Toyota XC90",
        color: "cyan",
        mileage: 77330,
        st: "West Virginia",
      },
    ],
  },
  {
    id: 5,
    name: "Connie Kub",
    email: "General1@hotmail.com",
    phone: "235-365-6015 x5135",
    avatar: "https://cdn.fakercloud.com/avatars/victor_haydin_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Mini Taurus",
        color: "indigo",
        mileage: 69311,
        st: "Tennessee",
      },
      {
        id: 2,
        designation: "Dodge Aventador",
        color: "azure",
        mileage: 3514,
        st: "Texas",
      },
      {
        id: 3,
        designation: "Mercedes Benz Ranchero",
        color: "magenta",
        mileage: 65055,
        st: "New Hampshire",
      },
      {
        id: 4,
        designation: "Rolls Royce Model 3",
        color: "salmon",
        mileage: 5876,
        st: "Washington",
      },
    ],
  },
  {
    id: 6,
    name: "Toby Dickinson",
    email: "Gayle64@yahoo.com",
    phone: "565-218-7802 x66970",
    avatar: "https://cdn.fakercloud.com/avatars/svenlen_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Land Rover Escalade",
        color: "ivory",
        mileage: 70644,
        st: "Maine",
      },
      {
        id: 2,
        designation: "Mercedes Benz Escalade",
        color: "lime",
        mileage: 76103,
        st: "Michigan",
      },
      {
        id: 3,
        designation: "Chevrolet A8",
        color: "ivory",
        mileage: 81504,
        st: "Alaska",
      },
    ],
  },
  {
    id: 7,
    name: "Warren Flatley",
    email: "Alanna_Bogan@hotmail.com",
    phone: "(912) 636-5232 x53111",
    avatar: "https://cdn.fakercloud.com/avatars/bargaorobalo_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Polestar Focus",
        color: "yellow",
        mileage: 24039,
        st: "Delaware",
      },
      {
        id: 2,
        designation: "Chevrolet Mercielago",
        color: "tan",
        mileage: 72860,
        st: "West Virginia",
      },
      {
        id: 3,
        designation: "Hyundai Volt",
        color: "tan",
        mileage: 24421,
        st: "Nebraska",
      },
      {
        id: 4,
        designation: "Cadillac Corvette",
        color: "cyan",
        mileage: 93123,
        st: "Indiana",
      },
    ],
  },
  {
    id: 8,
    name: "Ronnie Labadie",
    email: "Alysa.Macejkovic@yahoo.com",
    phone: "242.892.2118 x5624",
    avatar: "https://cdn.fakercloud.com/avatars/barputro_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Jaguar Ranchero",
        color: "white",
        mileage: 77161,
        st: "New York",
      },
      {
        id: 2,
        designation: "Bentley Escalade",
        color: "pink",
        mileage: 14581,
        st: "Maryland",
      },
      {
        id: 3,
        designation: "Maserati XC90",
        color: "turquoise",
        mileage: 55327,
        st: "Kansas",
      },
    ],
  },
  {
    id: 9,
    name: "Mathew Berge",
    email: "Emilie_Schuster@yahoo.com",
    phone: "(408) 940-7296",
    avatar: "https://cdn.fakercloud.com/avatars/gonzalorobaina_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Aston Martin Impala",
        color: "lime",
        mileage: 53654,
        st: "Idaho",
      },
    ],
  },
  {
    id: 10,
    name: "Stacy Corwin IV",
    email: "Abbigail_Schowalter@hotmail.com",
    phone: "1-468-603-1857 x698",
    avatar: "https://cdn.fakercloud.com/avatars/larrygerard_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Aston Martin Mercielago",
        color: "orchid",
        mileage: 1158,
        st: "Florida",
      },
      {
        id: 2,
        designation: "Honda Camry",
        color: "azure",
        mileage: 38226,
        st: "South Dakota",
      },
      {
        id: 3,
        designation: "Ferrari Altima",
        color: "mint green",
        mileage: 15046,
        st: "New Jersey",
      },
      {
        id: 4,
        designation: "Cadillac XC90",
        color: "plum",
        mileage: 62686,
        st: "Wisconsin",
      },
      {
        id: 5,
        designation: "Bentley Element",
        color: "orchid",
        mileage: 26129,
        st: "Michigan",
      },
    ],
  },
  {
    id: 11,
    name: "Terence Windler",
    email: "Melyna36@gmail.com",
    phone: "1-594-745-9106 x17276",
    avatar: "https://cdn.fakercloud.com/avatars/thierrymeier__128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Ford Civic",
        color: "green",
        mileage: 63172,
        st: "Arizona",
      },
      {
        id: 2,
        designation: "Jeep Impala",
        color: "sky blue",
        mileage: 58746,
        st: "Texas",
      },
      {
        id: 3,
        designation: "Mercedes Benz XC90",
        color: "grey",
        mileage: 50677,
        st: "Idaho",
      },
      {
        id: 4,
        designation: "Aston Martin V90",
        color: "maroon",
        mileage: 7517,
        st: "Hawaii",
      },
    ],
  },
  {
    id: 12,
    name: "Al Bahringer",
    email: "Green.Stokes@gmail.com",
    phone: "(826) 387-5810",
    avatar: "https://cdn.fakercloud.com/avatars/2fockus_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Volvo Expedition",
        color: "olive",
        mileage: 9467,
        st: "Hawaii",
      },
      {
        id: 2,
        designation: "Honda Volt",
        color: "gold",
        mileage: 39968,
        st: "New Hampshire",
      },
      {
        id: 3,
        designation: "Toyota Taurus",
        color: "pink",
        mileage: 91369,
        st: "Louisiana",
      },
    ],
  },
  {
    id: 13,
    name: "Miss Byron Crooks",
    email: "Jarvis.Welch@gmail.com",
    phone: "(949) 440-8481 x378",
    avatar: "https://cdn.fakercloud.com/avatars/weavermedia_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Jaguar Explorer",
        color: "orange",
        mileage: 60690,
        st: "Massachusetts",
      },
      {
        id: 2,
        designation: "Tesla Wrangler",
        color: "maroon",
        mileage: 23536,
        st: "Arkansas",
      },
    ],
  },
  {
    id: 14,
    name: "Mona Crooks",
    email: "Dortha51@gmail.com",
    phone: "981-451-9665 x063",
    avatar: "https://cdn.fakercloud.com/avatars/davidbaldie_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Ferrari Focus",
        color: "gold",
        mileage: 68024,
        st: "Ohio",
      },
      {
        id: 2,
        designation: "Tesla Challenger",
        color: "grey",
        mileage: 24818,
        st: "Nebraska",
      },
      {
        id: 3,
        designation: "Bugatti Camaro",
        color: "pink",
        mileage: 97791,
        st: "South Dakota",
      },
      {
        id: 4,
        designation: "Land Rover Beetle",
        color: "turquoise",
        mileage: 20523,
        st: "Iowa",
      },
      {
        id: 5,
        designation: "Smart A4",
        color: "grey",
        mileage: 26529,
        st: "South Carolina",
      },
    ],
  },
  {
    id: 15,
    name: "Rick Jakubowski",
    email: "Axel80@gmail.com",
    phone: "324.427.6096 x857",
    avatar: "https://cdn.fakercloud.com/avatars/increase_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Bugatti Beetle",
        color: "sky blue",
        mileage: 16263,
        st: "New Jersey",
      },
      {
        id: 2,
        designation: "Kia Ranchero",
        color: "fuchsia",
        mileage: 54787,
        st: "Missouri",
      },
      {
        id: 3,
        designation: "Rolls Royce XC90",
        color: "olive",
        mileage: 44290,
        st: "Maryland",
      },
      {
        id: 4,
        designation: "Bugatti Explorer",
        color: "salmon",
        mileage: 67899,
        st: "Louisiana",
      },
      {
        id: 5,
        designation: "Smart Ranchero",
        color: "white",
        mileage: 82726,
        st: "Virginia",
      },
    ],
  },
  {
    id: 16,
    name: "Lewis O'Hara DDS",
    email: "Ellen10@hotmail.com",
    phone: "363.532.3696 x972",
    avatar: "https://cdn.fakercloud.com/avatars/geobikas_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Audi ATS",
        color: "red",
        mileage: 74485,
        st: "Georgia",
      },
      {
        id: 2,
        designation: "Ford Camaro",
        color: "lime",
        mileage: 68188,
        st: "Pennsylvania",
      },
    ],
  },
  {
    id: 17,
    name: "Owen Pacocha",
    email: "Domenico3@yahoo.com",
    phone: "(460) 806-2921 x4808",
    avatar: "https://cdn.fakercloud.com/avatars/osmond_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Dodge Grand Caravan",
        color: "salmon",
        mileage: 15599,
        st: "Pennsylvania",
      },
      {
        id: 2,
        designation: "Chevrolet Jetta",
        color: "turquoise",
        mileage: 65613,
        st: "West Virginia",
      },
      {
        id: 3,
        designation: "Audi Colorado",
        color: "red",
        mileage: 18739,
        st: "Connecticut",
      },
    ],
  },
  {
    id: 18,
    name: "Brendan Kertzmann",
    email: "Ben48@gmail.com",
    phone: "1-895-365-4684 x04807",
    avatar: "https://cdn.fakercloud.com/avatars/marlinjayakody_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Kia Model 3",
        color: "purple",
        mileage: 86315,
        st: "Rhode Island",
      },
      {
        id: 2,
        designation: "Cadillac Volt",
        color: "grey",
        mileage: 1847,
        st: "Maryland",
      },
    ],
  },
  {
    id: 19,
    name: "Theodore Welch",
    email: "Cheyanne26@yahoo.com",
    phone: "(970) 573-1409 x967",
    avatar: "https://cdn.fakercloud.com/avatars/g3d_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Mazda A8",
        color: "lime",
        mileage: 43555,
        st: "Arkansas",
      },
    ],
  },
  {
    id: 20,
    name: "Bonnie Beer",
    email: "Florencio_Zboncak59@yahoo.com",
    phone: "(680) 556-5777",
    avatar: "https://cdn.fakercloud.com/avatars/kumarrajan12123_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Jeep Model T",
        color: "blue",
        mileage: 95320,
        st: "Ohio",
      },
      {
        id: 2,
        designation: "Smart Mustang",
        color: "purple",
        mileage: 58991,
        st: "Texas",
      },
    ],
  },
  {
    id: 21,
    name: "Santiago Barrows",
    email: "Kailee_Leannon18@hotmail.com",
    phone: "1-270-894-7000 x1732",
    avatar: "https://cdn.fakercloud.com/avatars/travis_arnold_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Aston Martin 911",
        color: "ivory",
        mileage: 68452,
        st: "Massachusetts",
      },
      {
        id: 2,
        designation: "Smart Impala",
        color: "blue",
        mileage: 7473,
        st: "Nevada",
      },
    ],
  },
  {
    id: 22,
    name: "Levi Adams",
    email: "Porter48@hotmail.com",
    phone: "823.732.3705 x2509",
    avatar: "https://cdn.fakercloud.com/avatars/mymyboy_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Toyota XC90",
        color: "blue",
        mileage: 91633,
        st: "New Hampshire",
      },
      {
        id: 2,
        designation: "BMW Volt",
        color: "indigo",
        mileage: 31314,
        st: "Wisconsin",
      },
      {
        id: 3,
        designation: "Cadillac Fiesta",
        color: "maroon",
        mileage: 50799,
        st: "New Hampshire",
      },
    ],
  },
  {
    id: 23,
    name: "Lela Crona II",
    email: "Orville_Emard@hotmail.com",
    phone: "762-216-3492 x117",
    avatar: "https://cdn.fakercloud.com/avatars/davidcazalis_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Chrysler Fortwo",
        color: "gold",
        mileage: 95677,
        st: "Nebraska",
      },
    ],
  },
  {
    id: 24,
    name: "Della Mertz",
    email: "Aletha.Harber@gmail.com",
    phone: "308.605.0944 x657",
    avatar: "https://cdn.fakercloud.com/avatars/Silveredge9_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Ford Mustang",
        color: "white",
        mileage: 94477,
        st: "Maryland",
      },
    ],
  },
  {
    id: 25,
    name: "Viola Jones",
    email: "Clint.Marquardt@yahoo.com",
    phone: "1-828-717-9560",
    avatar: "https://cdn.fakercloud.com/avatars/andrewofficer_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Hyundai ATS",
        color: "orchid",
        mileage: 68552,
        st: "Hawaii",
      },
      {
        id: 2,
        designation: "Mazda El Camino",
        color: "silver",
        mileage: 22712,
        st: "Arizona",
      },
      {
        id: 3,
        designation: "Mercedes Benz Volt",
        color: "maroon",
        mileage: 52792,
        st: "Colorado",
      },
      {
        id: 4,
        designation: "Chrysler El Camino",
        color: "teal",
        mileage: 89716,
        st: "Rhode Island",
      },
      {
        id: 5,
        designation: "Maserati PT Cruiser",
        color: "tan",
        mileage: 30489,
        st: "Nebraska",
      },
    ],
  },
  {
    id: 26,
    name: "Orville Lynch",
    email: "Ernie37@gmail.com",
    phone: "1-690-449-9379 x039",
    avatar: "https://cdn.fakercloud.com/avatars/ciaranr_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Chevrolet Model T",
        color: "ivory",
        mileage: 33867,
        st: "Hawaii",
      },
      {
        id: 2,
        designation: "Mazda Camry",
        color: "purple",
        mileage: 19293,
        st: "Utah",
      },
    ],
  },
  {
    id: 27,
    name: "Evan Nikolaus DDS",
    email: "Dora_Weber@yahoo.com",
    phone: "1-856-425-5216 x55613",
    avatar: "https://cdn.fakercloud.com/avatars/spacewood__128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Hyundai Durango",
        color: "yellow",
        mileage: 39161,
        st: "Louisiana",
      },
    ],
  },
  {
    id: 28,
    name: "Mr. Michael Pacocha",
    email: "Michael_Zulauf@hotmail.com",
    phone: "674-381-2785 x767",
    avatar: "https://cdn.fakercloud.com/avatars/karsh_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Rolls Royce Countach",
        color: "indigo",
        mileage: 4637,
        st: "Michigan",
      },
      {
        id: 2,
        designation: "Honda ATS",
        color: "grey",
        mileage: 26092,
        st: "North Dakota",
      },
    ],
  },
  {
    id: 29,
    name: "Edna Wyman",
    email: "Theodora_Franecki55@gmail.com",
    phone: "(504) 224-7095 x320",
    avatar: "https://cdn.fakercloud.com/avatars/kennyadr_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "BMW F-150",
        color: "violet",
        mileage: 81944,
        st: "Missouri",
      },
      {
        id: 2,
        designation: "Polestar Beetle",
        color: "grey",
        mileage: 18281,
        st: "South Carolina",
      },
      {
        id: 3,
        designation: "Dodge Wrangler",
        color: "lime",
        mileage: 359,
        st: "New York",
      },
    ],
  },
  {
    id: 30,
    name: "Tara Schuster",
    email: "Domingo_Berge35@yahoo.com",
    phone: "272.921.9451 x069",
    avatar: "https://cdn.fakercloud.com/avatars/gabrielizalo_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Mazda Wrangler",
        color: "pink",
        mileage: 83320,
        st: "Alaska",
      },
      {
        id: 2,
        designation: "Mini LeBaron",
        color: "plum",
        mileage: 80114,
        st: "Maine",
      },
      {
        id: 3,
        designation: "Maserati CX-9",
        color: "turquoise",
        mileage: 60800,
        st: "Arizona",
      },
      {
        id: 4,
        designation: "Volvo CTS",
        color: "azure",
        mileage: 28893,
        st: "Colorado",
      },
    ],
  },
  {
    id: 31,
    name: "Shane Bernier",
    email: "Breanne_Rice75@gmail.com",
    phone: "1-798-558-9568",
    avatar: "https://cdn.fakercloud.com/avatars/terrorpixel_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Rolls Royce Explorer",
        color: "green",
        mileage: 5757,
        st: "Washington",
      },
      {
        id: 2,
        designation: "Chevrolet Expedition",
        color: "magenta",
        mileage: 15573,
        st: "New Jersey",
      },
      {
        id: 3,
        designation: "Ferrari Mercielago",
        color: "green",
        mileage: 10762,
        st: "Kansas",
      },
      {
        id: 4,
        designation: "Smart Alpine",
        color: "azure",
        mileage: 57727,
        st: "Nebraska",
      },
      {
        id: 5,
        designation: "Maserati Volt",
        color: "magenta",
        mileage: 51484,
        st: "Idaho",
      },
    ],
  },
  {
    id: 32,
    name: "Tami Shanahan",
    email: "Ruth5@hotmail.com",
    phone: "(286) 731-7174 x918",
    avatar: "https://cdn.fakercloud.com/avatars/tbakdesigns_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Bugatti Challenger",
        color: "olive",
        mileage: 97414,
        st: "Wisconsin",
      },
      {
        id: 2,
        designation: "Mercedes Benz Altima",
        color: "blue",
        mileage: 79826,
        st: "South Carolina",
      },
      {
        id: 3,
        designation: "Kia A8",
        color: "silver",
        mileage: 41928,
        st: "Louisiana",
      },
      {
        id: 4,
        designation: "Tesla Model 3",
        color: "gold",
        mileage: 5514,
        st: "Vermont",
      },
    ],
  },
  {
    id: 33,
    name: "Dr. Melvin Jerde",
    email: "Doug_OReilly54@gmail.com",
    phone: "(810) 659-1286",
    avatar: "https://cdn.fakercloud.com/avatars/gcmorley_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Cadillac Fortwo",
        color: "lavender",
        mileage: 19791,
        st: "Alabama",
      },
      {
        id: 2,
        designation: "Porsche Fiesta",
        color: "turquoise",
        mileage: 40369,
        st: "Nevada",
      },
      {
        id: 3,
        designation: "Jaguar Accord",
        color: "plum",
        mileage: 16718,
        st: "West Virginia",
      },
      {
        id: 4,
        designation: "Maserati Expedition",
        color: "turquoise",
        mileage: 9658,
        st: "Vermont",
      },
    ],
  },
  {
    id: 34,
    name: "Iris VonRueden",
    email: "Vidal.Shields63@gmail.com",
    phone: "757.261.8085",
    avatar: "https://cdn.fakercloud.com/avatars/vitorleal_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Dodge Civic",
        color: "violet",
        mileage: 68800,
        st: "South Dakota",
      },
      {
        id: 2,
        designation: "Honda Wrangler",
        color: "black",
        mileage: 5019,
        st: "Mississippi",
      },
      {
        id: 3,
        designation: "Fiat Land Cruiser",
        color: "tan",
        mileage: 22064,
        st: "Texas",
      },
    ],
  },
  {
    id: 35,
    name: "Mindy Boyer III",
    email: "Solon11@hotmail.com",
    phone: "604.916.9478 x10490",
    avatar: "https://cdn.fakercloud.com/avatars/davecraige_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Mazda Land Cruiser",
        color: "orchid",
        mileage: 41336,
        st: "Texas",
      },
      {
        id: 2,
        designation: "Dodge F-150",
        color: "purple",
        mileage: 90041,
        st: "Delaware",
      },
    ],
  },
  {
    id: 36,
    name: "Marcus Sanford V",
    email: "Maurice98@gmail.com",
    phone: "1-573-923-7936",
    avatar: "https://cdn.fakercloud.com/avatars/idiot_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Nissan Impala",
        color: "grey",
        mileage: 93,
        st: "Arizona",
      },
      {
        id: 2,
        designation: "Kia Sentra",
        color: "white",
        mileage: 45254,
        st: "Georgia",
      },
    ],
  },
  {
    id: 37,
    name: "Bernice Wisozk",
    email: "Natalie.Kunze@hotmail.com",
    phone: "(519) 719-3185 x2738",
    avatar: "https://cdn.fakercloud.com/avatars/vikasvinfotech_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Bentley Colorado",
        color: "teal",
        mileage: 98985,
        st: "Wyoming",
      },
      {
        id: 2,
        designation: "Lamborghini Ranchero",
        color: "indigo",
        mileage: 13417,
        st: "North Dakota",
      },
      {
        id: 3,
        designation: "Kia Colorado",
        color: "black",
        mileage: 38445,
        st: "Indiana",
      },
    ],
  },
  {
    id: 38,
    name: "Dr. Ricardo McKenzie",
    email: "Christopher_Jakubowski56@yahoo.com",
    phone: "393-369-3007 x70926",
    avatar: "https://cdn.fakercloud.com/avatars/m4rio_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Jeep Malibu",
        color: "olive",
        mileage: 12023,
        st: "Minnesota",
      },
    ],
  },
  {
    id: 39,
    name: "Carlos Herman",
    email: "Nicholaus39@hotmail.com",
    phone: "556-553-2824 x995",
    avatar: "https://cdn.fakercloud.com/avatars/osmond_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Toyota Expedition",
        color: "cyan",
        mileage: 38385,
        st: "Michigan",
      },
      {
        id: 2,
        designation: "Volkswagen Beetle",
        color: "azure",
        mileage: 92877,
        st: "Rhode Island",
      },
    ],
  },
  {
    id: 40,
    name: "Alexandra Cronin MD",
    email: "Esta_Lebsack73@hotmail.com",
    phone: "1-432-303-8185 x6862",
    avatar: "https://cdn.fakercloud.com/avatars/saulihirvi_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Polestar Ranchero",
        color: "teal",
        mileage: 21911,
        st: "Kansas",
      },
      {
        id: 2,
        designation: "Volvo Aventador",
        color: "sky blue",
        mileage: 78523,
        st: "Virginia",
      },
      {
        id: 3,
        designation: "BMW Grand Caravan",
        color: "gold",
        mileage: 78727,
        st: "North Carolina",
      },
    ],
  },
  {
    id: 41,
    name: "Ron Carroll",
    email: "Christopher_Powlowski@hotmail.com",
    phone: "(412) 303-4572 x2700",
    avatar: "https://cdn.fakercloud.com/avatars/renbyrd_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Kia Challenger",
        color: "ivory",
        mileage: 18963,
        st: "Alabama",
      },
    ],
  },
  {
    id: 42,
    name: "Philip Ernser",
    email: "Gage.McCullough34@hotmail.com",
    phone: "1-213-722-8141",
    avatar: "https://cdn.fakercloud.com/avatars/pehamondello_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Polestar Silverado",
        color: "teal",
        mileage: 90837,
        st: "Iowa",
      },
      {
        id: 2,
        designation: "Aston Martin 1",
        color: "violet",
        mileage: 34658,
        st: "Vermont",
      },
      {
        id: 3,
        designation: "Honda Mercielago",
        color: "mint green",
        mileage: 65879,
        st: "Georgia",
      },
    ],
  },
  {
    id: 43,
    name: "Harvey Schaden DVM",
    email: "Otto_Stamm49@hotmail.com",
    phone: "909-801-0024",
    avatar: "https://cdn.fakercloud.com/avatars/albertaugustin_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Tesla F-150",
        color: "plum",
        mileage: 13106,
        st: "Iowa",
      },
      {
        id: 2,
        designation: "Lamborghini Prius",
        color: "yellow",
        mileage: 23018,
        st: "Idaho",
      },
      {
        id: 3,
        designation: "Ford Malibu",
        color: "ivory",
        mileage: 18189,
        st: "Utah",
      },
      {
        id: 4,
        designation: "Fiat 2",
        color: "pink",
        mileage: 43346,
        st: "Minnesota",
      },
    ],
  },
  {
    id: 44,
    name: "Warren Schaefer PhD",
    email: "Katarina_Langworth68@gmail.com",
    phone: "1-419-563-1363 x223",
    avatar: "https://cdn.fakercloud.com/avatars/ehsandiary_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Hyundai Civic",
        color: "red",
        mileage: 46283,
        st: "Montana",
      },
      {
        id: 2,
        designation: "Nissan Mercielago",
        color: "indigo",
        mileage: 50654,
        st: "New Hampshire",
      },
      {
        id: 3,
        designation: "Volkswagen Sentra",
        color: "black",
        mileage: 60727,
        st: "Missouri",
      },
    ],
  },
  {
    id: 45,
    name: "Myrtle Marks",
    email: "Lori89@yahoo.com",
    phone: "1-672-351-2164 x130",
    avatar: "https://cdn.fakercloud.com/avatars/yesmeck_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Volvo Grand Caravan",
        color: "azure",
        mileage: 43274,
        st: "Kentucky",
      },
      {
        id: 2,
        designation: "Mazda Prius",
        color: "orchid",
        mileage: 59891,
        st: "Georgia",
      },
      {
        id: 3,
        designation: "Nissan Colorado",
        color: "cyan",
        mileage: 98478,
        st: "New Hampshire",
      },
      {
        id: 4,
        designation: "Tesla Element",
        color: "purple",
        mileage: 33249,
        st: "Montana",
      },
    ],
  },
  {
    id: 46,
    name: "Miss Lois Sauer",
    email: "Joanny_Durgan68@hotmail.com",
    phone: "(641) 564-3629 x822",
    avatar: "https://cdn.fakercloud.com/avatars/gauravjassal_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Land Rover Model 3",
        color: "salmon",
        mileage: 31160,
        st: "West Virginia",
      },
      {
        id: 2,
        designation: "Jeep Explorer",
        color: "orchid",
        mileage: 27920,
        st: "Michigan",
      },
      {
        id: 3,
        designation: "Volkswagen ATS",
        color: "pink",
        mileage: 83632,
        st: "Virginia",
      },
    ],
  },
  {
    id: 47,
    name: "Esther Wolf Sr.",
    email: "Margaret.Mitchell65@hotmail.com",
    phone: "1-923-208-3563 x70395",
    avatar: "https://cdn.fakercloud.com/avatars/michaelcolenso_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Porsche Roadster",
        color: "teal",
        mileage: 77922,
        st: "North Dakota",
      },
      {
        id: 2,
        designation: "Mercedes Benz V90",
        color: "violet",
        mileage: 97082,
        st: "Nevada",
      },
      {
        id: 3,
        designation: "Bentley 1",
        color: "plum",
        mileage: 38132,
        st: "Maine",
      },
      {
        id: 4,
        designation: "Jeep Fiesta",
        color: "fuchsia",
        mileage: 58743,
        st: "Louisiana",
      },
    ],
  },
  {
    id: 48,
    name: "Gretchen Schaefer",
    email: "Audie15@yahoo.com",
    phone: "1-529-287-4512",
    avatar: "https://cdn.fakercloud.com/avatars/aluisio_azevedo_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Hyundai Colorado",
        color: "teal",
        mileage: 72118,
        st: "Utah",
      },
      {
        id: 2,
        designation: "Chevrolet 911",
        color: "cyan",
        mileage: 7864,
        st: "Massachusetts",
      },
      {
        id: 3,
        designation: "Aston Martin Accord",
        color: "lavender",
        mileage: 7229,
        st: "Delaware",
      },
      {
        id: 4,
        designation: "Maserati ATS",
        color: "grey",
        mileage: 59399,
        st: "Oklahoma",
      },
    ],
  },
  {
    id: 49,
    name: "Nicholas Turcotte III",
    email: "Kailee96@yahoo.com",
    phone: "363.476.8948 x49450",
    avatar: "https://cdn.fakercloud.com/avatars/meln1ks_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Audi Silverado",
        color: "salmon",
        mileage: 95131,
        st: "West Virginia",
      },
      {
        id: 2,
        designation: "Mazda ATS",
        color: "gold",
        mileage: 72400,
        st: "California",
      },
      {
        id: 3,
        designation: "Lamborghini Model T",
        color: "ivory",
        mileage: 31996,
        st: "Maine",
      },
      {
        id: 4,
        designation: "Honda Cruze",
        color: "black",
        mileage: 65501,
        st: "Hawaii",
      },
    ],
  },
  {
    id: 50,
    name: "Mrs. Darrel Johnston",
    email: "Esmeralda_McKenzie7@gmail.com",
    phone: "783-894-9421",
    avatar: "https://cdn.fakercloud.com/avatars/strikewan_128.jpg",
    vehicles: [
      {
        id: 1,
        designation: "Honda Corvette",
        color: "maroon",
        mileage: 1563,
        st: "Nebraska",
      },
      {
        id: 2,
        designation: "Chrysler Roadster",
        color: "yellow",
        mileage: 83241,
        st: "Idaho",
      },
    ],
  },
];
